{"uid":"5ea334a2bd642520","name":"Intentar convertir una cantidad negativa","fullName":"Gestión de monedas: Intentar convertir una cantidad negativa","historyId":"8d414140179c00af36a2d4d15ce13002","time":{"start":1732865902865,"stop":1732865902870,"duration":5},"status":"broken","statusMessage":"AttributeError: 'Context' object has no attribute 'error_message'\n","statusTrace":"  File \"C:\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\currency_manager_steps.py\", line 68, in step_impl\n    assert context.error_message == \"La cantidad debe ser positiva.\"  # Verificamos el error de cantidad negativa\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":4,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"AttributeError: 'Context' object has no attribute 'error_message'\n","statusTrace":"  File \"C:\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\currency_manager_steps.py\", line 68, in step_impl\n    assert context.error_message == \"La cantidad debe ser positiva.\"  # Verificamos el error de cantidad negativa\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n","steps":[{"name":"Given un usuario intenta convertir -50 USD a EUR","time":{"start":1732865902866,"stop":1732865902866,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"stepsCount":0,"hasContent":false,"attachmentsCount":0,"shouldDisplayMessage":false},{"name":"When realiza la conversión","time":{"start":1732865902866,"stop":1732865902866,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"stepsCount":0,"hasContent":false,"attachmentsCount":0,"shouldDisplayMessage":false},{"name":"Then se muestra un mensaje indicando que la cantidad debe ser positiva","time":{"start":1732865902866,"stop":1732865902869,"duration":3},"status":"broken","statusMessage":"AttributeError: 'Context' object has no attribute 'error_message'\n","statusTrace":"  File \"C:\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\currency_manager_steps.py\", line 68, in step_impl\n    assert context.error_message == \"La cantidad debe ser positiva.\"  # Verificamos el error de cantidad negativa\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"stepsCount":0,"hasContent":true,"attachmentsCount":0,"shouldDisplayMessage":true}],"attachments":[],"parameters":[],"attachmentStep":false,"stepsCount":3,"hasContent":true,"attachmentsCount":0,"shouldDisplayMessage":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Gestión de monedas"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"e8aac4f0891fa14a","status":"broken","statusDetails":"AttributeError: 'Context' object has no attribute 'error_message'\n","time":{"start":1732864772865,"stop":1732864772870,"duration":5}},{"uid":"f75cf4f103c2b4c8","status":"broken","statusDetails":"AttributeError: 'Context' object has no attribute 'error_message'\n","time":{"start":1732864689124,"stop":1732864689127,"duration":3}},{"uid":"80970b632c82e6cc","status":"broken","statusDetails":"AttributeError: 'Context' object has no attribute 'error_message'\n","time":{"start":1732863642166,"stop":1732863642170,"duration":4}},{"uid":"247708028584b8d5","status":"broken","statusDetails":"AttributeError: 'Context' object has no attribute 'error_message'\n","time":{"start":1732862762799,"stop":1732862762802,"duration":3}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"5ea334a2bd642520.json","parameterValues":[]}